TARDIS:LoadFolder("parts/tardis2010/controls-functional", false, true)
TARDIS:LoadFolder("parts/tardis2010/controls", false, true)
TARDIS:LoadFolder("parts/tardis2010/lights", false, true)
TARDIS:LoadFolder("parts/tardis2010/animated", false, true)
TARDIS:LoadFolder("parts/tardis2010/static", false, true)
TARDIS:LoadFolder("parts/tardis2010/corridors", false, true)